name: Python package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: release
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          poetry install --with=dev --with=test
      - name: Test with pytest
        run: |
          poetry run pytest